// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.vision.face.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The status of long running operation.
 */
public final class FaceOperationState extends ExpandableStringEnum<FaceOperationState> {
    /**
     * The operation is not started.
     */
    @Generated
    public static final FaceOperationState NOT_STARTED = fromString("notStarted");

    /**
     * The operation is still running.
     */
    @Generated
    public static final FaceOperationState RUNNING = fromString("running");

    /**
     * The operation is succeeded.
     */
    @Generated
    public static final FaceOperationState SUCCEEDED = fromString("succeeded");

    /**
     * The operation is failed.
     */
    @Generated
    public static final FaceOperationState FAILED = fromString("failed");

    /**
     * Creates a new instance of FaceOperationState value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public FaceOperationState() {
    }

    /**
     * Creates or finds a FaceOperationState from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding FaceOperationState.
     */
    @Generated
    public static FaceOperationState fromString(String name) {
        return fromString(name, FaceOperationState.class);
    }

    /**
     * Gets known FaceOperationState values.
     * 
     * @return known FaceOperationState values.
     */
    @Generated
    public static Collection<FaceOperationState> values() {
        return values(FaceOperationState.class);
    }
}
