// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.vision.face.implementation.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;

/**
 * Request of liveness with verify session creation.
 */
@Immutable
public final class LivenessSessionWithVerifyImageCreationContent {
    /*
     * The parameters for creating session.
     */
    @Generated
    private final LivenessSessionCreationContentForMultipart parameters;

    /*
     * The image stream for verify. Content-Disposition header field for this part must have filename.
     */
    @Generated
    private final VerifyImageFileDetails verifyImage;

    /**
     * Creates an instance of LivenessSessionWithVerifyImageCreationContent class.
     * 
     * @param parameters the parameters value to set.
     * @param verifyImage the verifyImage value to set.
     */
    @Generated
    public LivenessSessionWithVerifyImageCreationContent(LivenessSessionCreationContentForMultipart parameters,
        VerifyImageFileDetails verifyImage) {
        this.parameters = parameters;
        this.verifyImage = verifyImage;
    }

    /**
     * Get the parameters property: The parameters for creating session.
     * 
     * @return the parameters value.
     */
    @Generated
    public LivenessSessionCreationContentForMultipart getParameters() {
        return this.parameters;
    }

    /**
     * Get the verifyImage property: The image stream for verify. Content-Disposition header field for this part must
     * have filename.
     * 
     * @return the verifyImage value.
     */
    @Generated
    public VerifyImageFileDetails getVerifyImage() {
        return this.verifyImage;
    }
}
